# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 23:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.IntegerField(choices=[(1, 'Aberto'), (2, 'Realizado'), (3, 'Enviado'), (4, 'Finalizado')], default=1, verbose_name='Status')),
                ('state', django_fsm.FSMIntegerField(default=1)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='bot.Session')),
            ],
        ),
    ]
