# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20170321_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='entrega',
            field=models.IntegerField(choices=[(1, 'MotoBoy'), (2, 'Retirar no local')], default=1, verbose_name='Tipo entrega'),
        ),
    ]
