# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='horario',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horario'),
        ),
    ]
