# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 01:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_auto_20170226_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productorder',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
