# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_auto_20170227_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='pedido',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pedidos.Pedido'),
        ),
    ]
