# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 03:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0005_auto_20170326_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
