class ClientStateEnum(object):
    ENVIAR_MENU = 20
    RECEBER_OPCAO_MENU = 21
    PEDIDO = 29
    PEDIDO_LISTA_PRODUTOS = 30
    PEDIDO_QUANTIDADE = 31
    PEDIDO_ENDERECO = 32
    PEDIDO_OBSERVACAO = 33
    PEDIDO_CONFIRMAR = 34

    CADASTRO_TELEFONE = 40
    CADASTRO_TELEFONE_RECEBER = 41
    CADASTRO_ENDERECO = 45
    CADASTRO_ENDERECO_RECEBER = 46

    MEUS_PEDIDOS = 50
