# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170225_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='profile',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='accounts.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
