# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20170225_2237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='updated',
            new_name='last_active',
        ),
    ]
